### ISSUE TITLE
Python 2 support really needed?

### ISSUE THREAD

**Issue by atombrella** [jparise/flake8-assertive#13]
Most of these asserts were introduced in Python 3, so does it even make sense to officially support Python 2? Not that it requires a lot of code changes, though. Just wondering.

**Comment by atombrella** [comment]
There are four (plus their negative assertions) that are only available in Python 3.
https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertIs

**Comment by jparise** [comment]
> There are four (plus their negative assertions) that are only available in Python 3.
> [docs.python.org/3/library/unittest.html#unittest.TestCase.assertIs](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertIs)

Those are also available in Python 2.7: https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertIs

They were introduced concurrently when both versions were under active development.
